[project]
name = "multi-agent-research-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
[tool.setuptools]
packages = ["agent", "config", "memory", "workflow", "prompt_library"]
package-dir = {"" = "src"}
